dist: trusty
language: node_js
git:
  depth: 3
node_js:
  - "8"
before_script:
  - gem install percy-cli
script:
  - npm run test
  - npm run snapshot
deploy:
  provider: surge
  project: ./dist
  domain: cupcake-design-system.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
